# Generated by Django 2.2.24 on 2021-06-20 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firt_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('age', models.IntegerField(max_length=10)),
                ('celphone', models.IntegerField(max_length=100)),
                ('birth_date', models.DateField(null=True)),
            ],
        ),
    ]
