# Generated by Django 2.2.24 on 2021-06-21 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_class_signed'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
